/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function applyViteDefineReplacements(
  code: string,
  defines: Array<DefineReplacementNapi>,
): string;

/** Art descriptor for NAPI */
export interface ArtDescriptorNapi {
  filename: string;
  metadata: ArtMetadataNapi;
  variants: Array<ArtVariantNapi>;
  hasScriptSetup: boolean;
  hasScript: boolean;
  styleCount: number;
}

/** Art metadata for NAPI */
export interface ArtMetadataNapi {
  title: string;
  description?: string;
  component?: string;
  category?: string;
  tags: Array<string>;
  status: string;
  order?: number;
}

/** Art parse options for NAPI */
export interface ArtParseOptionsNapi {
  filename?: string;
}

/** Transform Art to Storybook CSF 3.0 */
export declare function artToCsf(
  source: string,
  options?: ArtParseOptionsNapi | undefined | null,
): CsfOutputNapi;

/** Art variant for NAPI */
export interface ArtVariantNapi {
  name: string;
  template: string;
  isDefault: boolean;
  skipVrt: boolean;
}

export interface AutogenConfigNapi {
  maxVariants?: number;
  includeDefault?: boolean;
  includeBooleanToggles?: boolean;
  includeEnumVariants?: boolean;
  includeBoundaryValues?: boolean;
  includeEmptyStrings?: boolean;
}

export interface AutogenOutputNapi {
  variants: Array<GeneratedVariantNapi>;
  artFileContent: string;
  componentName: string;
}

export interface BatchCompileOptionsNapi {
  mode?: string;
  ssr?: boolean;
  vapor?: boolean;
  customRenderer?: boolean;
  customElements?: Array<string>;
  templateSyntax?: string;
  experimentalInTagComments?: boolean;
  experimentalPatternedTemplate?: boolean;
  experimentalServerScript?: boolean;
  runtimeModuleName?: string;
  runtimeGlobalName?: string;
  vueVersion?: string;
  /** Preserve TypeScript in output when true */
  isTs?: boolean;
  /** Worker threads for this call (1-256). Omit to use Rayon's global pool.
   * Concurrent explicit calls share a process-wide 256-worker budget.
   * Capacity exhaustion fails immediately with a `WouldDeadlock` error. */
  threads?: number;
  /**
   * Include per-block style metadata (incl. `styles[].content`). Default OFF.
   *
   * `code`/`css` are always materialized; the per-block `styles` payload
   * re-sends the raw CSS that `css` already carries, so the default boundary
   * omits it to avoid duplicate UTF-8 -> V8 copies. Consumers that need the
   * preprocessor/CSS-modules metadata opt in explicitly.
   */
  includeStyles?: boolean;
  /** Include parsed custom blocks. Default OFF. */
  includeCustomBlocks?: boolean;
  /** Include compile-time macro artifacts. Default OFF. */
  includeMacroArtifacts?: boolean;
  /** Include template/style/script content hashes (for HMR). Default OFF. */
  includeHashes?: boolean;
  /**
   * Emit a Source Map v3 document per file (`map`). Default OFF.
   *
   * The pre-compile batch is the path every build takes, so a production
   * build with `build.sourcemap` on has to be able to ask for maps here or
   * the bundle's maps point at the virtual module instead of the `.vue`
   * file (#3399).
   */
  includeSourceMap?: boolean;
}

export interface BatchCompileResultNapi {
  success: number;
  failed: number;
  inputBytes: number;
  outputBytes: number;
  timeMs: number;
}

export interface BatchCompileResultWithFilesNapi {
  results: Array<BatchFileResultNapi>;
  successCount: number;
  failedCount: number;
  timeMs: number;
}

export interface BatchFileInputNapi {
  path: string;
  source: string;
}

export interface BatchFileResultNapi {
  path: string;
  code: string;
  /** Source Map v3 document (JSON) describing `code`, present only when
   * `includeSourceMap` was requested and a line could be anchored (#3399). */
  map?: string;
  css?: string;
  scopeId: string;
  hasScoped: boolean;
  errors: Array<string>;
  warnings: Array<string>;
  templateHash?: string;
  styleHash?: string;
  scriptHash?: string;
  styles: Array<StyleBlockNapi>;
  customBlocks: Array<CustomBlockNapi>;
  macroArtifacts: Array<MacroArtifactNapi>;
}

/** Batch type check result for NAPI */
export interface BatchTypeCheckResultNapi {
  filesChecked: number;
  filesWithErrors: number;
  totalErrors: number;
  totalWarnings: number;
  timeMs: number;
}

export declare function buildDesignTokenMap(categories: string): string;

export declare function buildInspectorGraph(
  files: Array<InspectorSourceFileNapi>,
): InspectorGraphNapi;

/** Resolve effective lint rules and provenance using Vize's execution matcher. */
export declare function inspectLintPlan(plan: string, root: string, files: Array<string>): string;

/** Catalog entry for NAPI */
export interface CatalogEntryNapi {
  title: string;
  description?: string;
  category?: string;
  tags: Array<string>;
  status: string;
  variantCount: number;
  docPath: string;
  sourcePath: string;
}

/** Catalog output for NAPI */
export interface CatalogOutputNapi {
  markdown: string;
  filename: string;
  componentCount: number;
  categories: Array<string>;
  tags: Array<string>;
}

export declare function chunkVitePrecompileFiles(
  files: Array<string>,
  batchSize?: number | undefined | null,
  options?: VitePrecompileChunkOptionsNapi | undefined | null,
): Array<Array<string>>;

export declare function classifyVitePluginRequest(id: string): VitePluginRequestNapi;

export declare function collectSfcTemplateAssetUrls(
  source: string,
  rules?: Array<TemplateAssetTagRuleNapi> | undefined | null,
  filename?: string | undefined | null,
): Array<TemplateAssetUrlNapi>;

/** Compile Vue template to VDom render function */
export declare function compile(
  template: string,
  options?: CompilerOptions | undefined | null,
): CompileResult;

export declare function compileCss(
  source: string,
  options?: CssCompileOptionsNapi | undefined | null,
): CssCompileResultNapi;

export declare function compileJsx(
  source: string,
  options?: JsxCompileOptionsNapi | undefined | null,
): JsxCompileResultNapi;

/** Compile result */
export interface CompileResult {
  /** Generated code */
  code: string;
  /** Preamble code (imports) */
  preamble: string;
  /** AST (serialized as JSON) */
  ast: any;
  /** Source map */
  map?: any;
  /** Used helpers */
  helpers: Array<string>;
  /** Template strings for Vapor mode static parts */
  templates?: Array<string>;
}

/** Compiler options for bindings */
export interface CompilerOptions {
  /** Output mode: "module" or "function" */
  mode?: string;
  /** Whether to prefix identifiers */
  prefixIdentifiers?: boolean;
  /** Whether to hoist static nodes */
  hoistStatic?: boolean;
  /** Whether to cache event handlers */
  cacheHandlers?: boolean;
  /** Scope ID for scoped CSS */
  scopeId?: string;
  /** Whether in SSR mode */
  ssr?: boolean;
  /** Whether to generate source map */
  sourceMap?: boolean;
  /** Filename for source map */
  filename?: string;
  /** Output mode: "vdom" or "vapor" */
  outputMode?: string;
  /** Whether the template contains TypeScript */
  isTs?: boolean;
  /** Whether the template targets a custom renderer instead of the DOM. */
  customRenderer?: boolean;
  /** Tag patterns that compile as custom elements instead of Vue components. */
  customElements?: Array<string>;
  /** Template syntax compatibility mode: "standard", "strict", or "quirks". */
  templateSyntax?: string;
  /** Enable experimental Vue in-tag comments (`// ...`) inside opening tags. */
  experimentalInTagComments?: boolean;
  /** Enable experimental `v-match` / `v-case` patterned template desugaring. */
  experimentalPatternedTemplate?: boolean;
  /** Enable experimental server-script related RFC surface. */
  experimentalServerScript?: boolean;
  /** Module name for runtime imports. */
  runtimeModuleName?: string;
  /** Global variable name for standalone/function mode. */
  runtimeGlobalName?: string;
  /**
   * Script extension handling: "preserve" (keep TypeScript) or "downcompile" (transpile to JS)
   * Defaults to "downcompile"
   */
  scriptExt?: string;
}

export declare function compileSfc(
  source: string,
  options?: SfcCompileOptionsNapi | undefined | null,
): SfcCompileResultNapi;

/**
 * Compiles a glob of Vue SFCs and returns aggregate stats for the native API.
 *
 * This stats-only surface is intentionally optimized differently from
 * `compileSfcBatchWithResults`: because no per-file code crosses the JS/native
 * boundary, repeated SFC bodies are grouped before parallel compilation. The
 * representative compile produces one output length, and the counters are
 * multiplied by the number of files that shared the same safe key.
 */
export declare function compileSfcBatch(
  pattern: string,
  options?: BatchCompileOptionsNapi | undefined | null,
): BatchCompileResultNapi;

export declare function compileSfcBatchWithResults(
  files: Array<BatchFileInputNapi>,
  options?: BatchCompileOptionsNapi | undefined | null,
): BatchCompileResultWithFilesNapi;

/** Compile Vue template to Vapor mode */
export declare function compileVapor(
  template: string,
  options?: CompilerOptions | undefined | null,
): CompileResult;

export declare function createViteBareImportBases(
  root: string,
  importer?: string | undefined | null,
): Array<string>;

export declare function createViteBareImportCandidates(
  id: string,
  aliasRules: Array<CssAliasRuleNapi>,
  resolvedId?: string | undefined | null,
): Array<string>;

export declare function createViteVirtualId(
  realPath: string,
  ssr?: boolean | undefined | null,
): string;

/** CSF output for NAPI */
export interface CsfOutputNapi {
  code: string;
  filename: string;
}

export interface CssAliasRuleNapi {
  find: string;
  replacement: string;
  isRegex: boolean;
  flags?: string;
}

export interface CssAstResultNapi {
  ast?: any;
  errors: Array<string>;
  warnings: Array<string>;
}

export interface CssCompileOptionsNapi {
  filename?: string;
  scoped?: boolean;
  scopeId?: string;
  sourceMap?: boolean;
  minify?: boolean;
  cssModules?: boolean;
  customMedia?: boolean;
  targets?: CssTargetsNapi;
}

export interface CssCompileResultNapi {
  code: string;
  map?: string;
  cssVars: Array<string>;
  errors: Array<string>;
  warnings: Array<string>;
}

export interface CssTargetsNapi {
  chrome?: number;
  firefox?: number;
  safari?: number;
  edge?: number;
  ios?: number;
  android?: number;
}

export interface CustomBlockNapi {
  blockType: string;
  content: string;
  src?: string;
  attrs: Array<SfcBlockAttributeNapi>;
  index: number;
}

/** Declaration generation options for NAPI */
export interface DeclarationOptionsNapi {
  filename?: string;
}

/** Declaration generation result for NAPI */
export interface DeclarationResultNapi {
  code: string;
}

export interface DefineReplacementNapi {
  key: string;
  value: string;
}

export declare function detectViteHmrUpdateType(
  prev: HmrHashesNapi | undefined | null,
  next: HmrHashesNapi,
): string;

export declare function diffVitePrecompileFiles(
  files: Array<string>,
  currentMetadata: Array<VitePrecompileFileMetadataEntryNapi>,
  previousMetadata: Array<VitePrecompileFileMetadataEntryNapi>,
): VitePrecompileDiffNapi;

/** Doc options for NAPI */
export interface DocOptionsNapi {
  includeSource?: boolean;
  includeTemplates?: boolean;
  includeMetadata?: boolean;
  includeToc?: boolean;
  tocThreshold?: number;
  basePath?: string;
  title?: string;
}

/** Doc output for NAPI */
export interface DocOutputNapi {
  markdown: string;
  filename: string;
  title: string;
  category?: string;
  variantCount: number;
}

export interface DynamicImportAliasRuleNapi {
  fromPrefix: string;
  toPrefix: string;
}

export declare function extractSfcCustomBlocks(
  source: string,
  filename?: string | undefined | null,
): Array<CustomBlockNapi>;

export declare function extractSfcSrcInfo(
  source: string,
  filename?: string | undefined | null,
): SfcSrcInfoNapi;

export declare function extractSfcStyleBlocks(
  source: string,
  filename?: string | undefined | null,
): Array<StyleBlockNapi>;

export declare function findDependentDesignTokens(
  tokenMap: string,
  targetPath: string,
): Array<string>;

export declare function flattenDesignTokenCategories(categories: string): string;

/** Format options for NAPI. */
export interface FormatOptionsNapi {
  printWidth?: number;
  tabWidth?: number;
  useTabs?: boolean;
  semi?: boolean;
  singleQuote?: boolean;
  sortAttributes?: boolean;
  singleAttributePerLine?: boolean;
  maxAttributesPerLine?: number;
  normalizeDirectiveShorthands?: boolean;
}

/** Format result for NAPI. */
export interface FormatResultNapi {
  code: string;
  changed: boolean;
}

/** Format a Vue SFC source string. */
export declare function formatSfc(
  source: string,
  options?: FormatOptionsNapi | undefined | null,
): FormatResultNapi;

export declare function fromViteVirtualId(virtualId: string): string;

/** Generate catalog from multiple Art sources (high-performance batch) */
export declare function generateArtCatalog(
  sources: Array<string>,
  docOptions?: DocOptionsNapi | undefined | null,
): CatalogOutputNapi;

/** Generate component documentation from Art source */
export declare function generateArtDoc(
  source: string,
  artOptions?: ArtParseOptionsNapi | undefined | null,
  docOptions?: DocOptionsNapi | undefined | null,
): DocOutputNapi;

/** Batch generate docs with parallel processing */
export declare function generateArtDocsBatch(
  sources: Array<string>,
  docOptions?: DocOptionsNapi | undefined | null,
): Array<DocOutputNapi>;

/** Generate props palette from Art source */
export declare function generateArtPalette(
  source: string,
  artOptions?: ArtParseOptionsNapi | undefined | null,
  paletteOptions?: PaletteOptionsNapi | undefined | null,
): PaletteOutputNapi;

/** Generate a Vue SFC `.d.ts` declaration from Croquis analysis. */
export declare function generateDeclaration(
  source: string,
  options?: DeclarationOptionsNapi | undefined | null,
): DeclarationResultNapi;

export declare function generateDesignTokensMarkdown(
  categories: string,
  generatedAt?: string | undefined | null,
): string;

export interface GeneratedVariantNapi {
  name: string;
  isDefault: boolean;
  props: any;
  description?: string;
}

export declare function generateSfcScopeId(
  filename: string,
  root?: string | undefined | null,
  isProduction?: boolean | undefined | null,
  source?: string | undefined | null,
): string;

/** Generate .art.vue variants from component prop definitions */
export declare function generateVariants(
  componentPath: string,
  props: Array<PropDefinitionNapi>,
  config?: AutogenConfigNapi | undefined | null,
): AutogenOutputNapi;

export declare function generateViteHmrCode(scopeId: string, updateType: string): string;

/** Get Patina's currently registered rule metadata. */
export declare function getPatinaRules(): any;

/** Get type checking capabilities info */
export declare function getTypeCheckCapabilities(): TypeCheckCapabilitiesNapi;

export declare function hasSfcScopedStyle(
  source: string,
  filename?: string | undefined | null,
): boolean;

export declare function hasViteHmrChanges(
  prev: HmrHashesNapi | undefined | null,
  next: HmrHashesNapi,
): boolean;

export declare function hasVitePrecompileFileMetadataChanged(
  previous: VitePrecompileFileMetadataNapi | undefined | null,
  next: VitePrecompileFileMetadataNapi,
): boolean;

export interface HmrHashesNapi {
  scriptHash?: string;
  templateHash?: string;
  styleHash?: string;
}

export declare function isBuiltinViteDefine(key: string): boolean;

export declare function isSfcImportableAssetUrl(url: string): boolean;

export declare function isViteBareSpecifier(id: string): boolean;

/** Options for [`compile_jsx`]. */
export interface JsxCompileOptionsNapi {
  /** Source filename, used to infer the language when `lang` is omitted. */
  filename?: string;
  /**
   * Source language: `"jsx"` or `"tsx"`. Defaults to `"jsx"` (or is inferred
   * from a `.tsx` `filename`).
   */
  lang?: string;
  /**
   * Default output mode: `"vdom"` (default) or `"vapor"`. Mirrors the
   * `compiler.jsxMode` config key and takes precedence over `vapor`.
   * Per-component `"use vue:vapor"` / `"use vue:vdom"` directives override it.
   */
  jsxMode?: string;
  /**
   * JSX semantics: `"native"` (default) or `"babel"`. Babel compatibility is
   * only defined for VDOM output.
   */
  jsxCompat?: "native" | "babel";
  /**
   * Legacy default-mode toggle: `true` compiles components to Vapor, `false`
   * (default) to VDOM. Kept for back-compat; prefer `jsxMode`. Ignored when
   * `jsxMode` is set.
   */
  vapor?: boolean;
  /**
   * Emit a v3 source map for the generated render code. When `true`, the
   * result's `map` carries the map JSON; when `false` (default), `map` is
   * `null` and no mapping work is done (#1533).
   */
  sourceMap?: boolean;
  /** Emit SSR render code instead of client render code. */
  ssr?: boolean;
}

/** Result of [`compile_jsx`]. */
export interface JsxCompileResultNapi {
  /**
   * Generated render code for the module: the deduplicated runtime-helper
   * preamble (`import { … } from "vue"`) followed by every component's render
   * code in source order. This is a self-contained module string, matching
   * the shape `compileSfc` returns, so a bundler can emit it directly
   * (the runtime-helper imports are no longer dropped, #1533).
   */
  code: string;
  /**
   * v3 source map (JSON) for `code`, present only when `sourceMap` was
   * requested and the module is a single component (the per-file shape the
   * bundler plugins consume). `null` otherwise (#1533).
   */
  map?: string;
  /** Error-severity diagnostic messages. */
  errors: Array<string>;
  /** Warning-severity diagnostic messages. */
  warnings: Array<string>;
  /**
   * Extracted `<style scoped>` blocks across the module's components, in
   * source order (#1495). Empty when no component had a `<style scoped>`. Each
   * entry's CSS is already scope-rewritten; the bundler plugins emit it
   * through the same path SFC styles use (#1533).
   */
  scopedStyles: Array<JsxScopedStyleNapi>;
}

/**
 * A JSX component's extracted `<style scoped>` block, surfaced to the bundler
 * plugins so a `.jsx`/`.tsx` component's scoped CSS reaches the same emission
 * path as SFC `<style>` blocks (#1495, #1533).
 */
export interface JsxScopedStyleNapi {
  /**
   * The generated scope id, e.g. `data-v-1a2b3c4d`. Already injected into the
   * component's rendered elements; surfaced here so the bundler can name the
   * emitted stylesheet deterministically.
   */
  scopeId: string;
  /**
   * The scoped-rewritten CSS, with the `data-v-<hash>` attribute already
   * applied to selectors. A bundler emits this verbatim.
   */
  css: string;
}

/** Lint Vue SFC files matching patterns (native multithreading, .gitignore-aware) */
export declare function lint(
  patterns: Array<string>,
  options?: LintOptionsNapi | undefined | null,
): LintResultNapi;

/** Lint options for NAPI */
export interface LintOptionsNapi {
  /** Output format: "text", "ansi", "plain", "json", "stylish", "markdown", "html", or "agent" */
  format?: string;
  /** Maximum number of warnings before failing */
  maxWarnings?: number;
  /** Quiet mode - only show summary */
  quiet?: boolean;
  /** Automatically fix problems when diagnostics provide safe text edits */
  fix?: boolean;
  /** Help display level: "full", "short", "none" */
  helpLevel?: string;
  /** Lint preset: "general-recommended", "essential", "incremental", "ecosystem", "opinionated", or "nuxt" */
  preset?: string;
  /** Enable native type-aware lint rules */
  typeAware?: boolean;
  /** Path to the Corsa executable used by type-aware lint rules */
  corsaPath?: string;
}

/** Lint a single Vue SFC with Patina and return structured diagnostics. */
export declare function lintPatinaSfc(
  source: string,
  options?: PatinaLintOptionsNapi | undefined | null,
): any;

/** Lint result for NAPI */
export interface LintResultNapi {
  /** Formatted output string */
  output: string;
  /** Total number of errors */
  errorCount: number;
  /** Total number of warnings */
  warningCount: number;
  /** Number of files linted */
  fileCount: number;
  /** Time in milliseconds */
  timeMs: number;
}

export interface MacroArtifactNapi {
  kind: string;
  name: string;
  source: string;
  content: string;
  moduleCode?: string;
  start: number;
  end: number;
}

export interface InspectorGraphEdgeNapi {
  from: string;
  to: string;
  kind: string;
  specifier: string;
}

export interface InspectorGraphNapi {
  nodes: Array<InspectorGraphNodeNapi>;
  edges: Array<InspectorGraphEdgeNapi>;
}

export interface InspectorGraphNodeNapi {
  path: string;
  kind: string;
  isEntry: boolean;
  sourceBytes: number;
  sourceLines: number;
}

export interface InspectorSourceFileNapi {
  path: string;
  source: string;
}

export declare function normalizeViteCssModuleFilename(filename: string): string;

export declare function normalizeViteDevMiddlewareUrl(
  reqUrl: string,
): ViteDevMiddlewareRewriteNapi | null;

export declare function normalizeViteFsIdForBuild(id: string): string;

export declare function normalizeVitePrecompileBatchSize(value?: number | undefined | null): number;

export declare function normalizeViteRequireBase(
  importer?: string | undefined | null,
): string | null;

export declare function normalizeViteResolvedVuePath(id: string): string | null;

export declare function normalizeViteVirtualVueModuleId(id: string): string;

/**
 * Normalize a raw `vize.config.*` export into the public resolved shape.
 *
 * The implementation works directly with NAPI values instead of serializing
 * through JSON. That keeps JavaScript-only values such as `RegExp` filters
 * intact while still moving the merge, null stripping, and legacy alias
 * handling out of the TypeScript loader.
 */
export declare function normalizeVizeConfig(value: unknown): unknown;

/** Palette options for NAPI */
export interface PaletteOptionsNapi {
  inferOptions?: boolean;
  minSelectValues?: number;
  maxSelectValues?: number;
  groupByType?: boolean;
}

/** Palette output for NAPI */
export interface PaletteOutputNapi {
  title: string;
  controls: Array<PropControlNapi>;
  groups: Array<string>;
  json: string;
  typescript: string;
}

/** Parse Art file (*.art.vue) */
export declare function parseArt(
  source: string,
  options?: ArtParseOptionsNapi | undefined | null,
): ArtDescriptorNapi;

/** Return unknown-status warnings for an Art file (`*.art.vue`). */
export declare function parseArtStatusWarnings(
  source: string,
  options?: ArtParseOptionsNapi | undefined | null,
): Array<string>;

export declare function parseCssAst(
  source: string,
  options?: CssCompileOptionsNapi | undefined | null,
): CssAstResultNapi;

export declare function parseDesignTokensFromJson(source: string): string;

export declare function parseDesignTokensFromPath(tokensPath: string): string;

export declare function parseSfc(
  source: string,
  options?: SfcParseOptionsNapi | undefined | null,
): any;

/** Parse template to AST only */
export declare function parseTemplate(
  template: string,
  options?: CompilerOptions | undefined | null,
): any;

/** Single-file Patina lint options for NAPI */
export interface PatinaLintOptionsNapi {
  /** Filename used for diagnostics */
  filename?: string;
  /** Locale code: "en", "ja", or "zh" */
  locale?: string;
  /** Help display level: "full", "short", or "none" */
  helpLevel?: string;
  /** Lint preset: "general-recommended", "essential", "incremental", "ecosystem", "opinionated", or "nuxt" */
  preset?: string;
  /** Optional list of Patina rule names to enable */
  enabledRules?: Array<string>;
  /** Enable native type-aware lint rules */
  typeAware?: boolean;
  /** Path to the Corsa executable used by type-aware lint rules */
  corsaPath?: string;
  /** Casing for `vue/component-name-in-template-casing`: "PascalCase" or "kebab-case" */
  componentNameInTemplateCasing?: string;
  /** Casing for `script/custom-event-name-casing`: "camelCase" or "kebab-case" */
  customEventNameCasing?: string;
  /** Options for `vue/html-self-closing` */
  htmlSelfClosing?: HtmlSelfClosingOptionsNapi;
}

/** HTML self-closing options for NAPI */
export interface HtmlSelfClosingOptionsNapi {
  html?: HtmlSelfClosingHtmlOptionsNapi;
  svg?: string;
  math?: string;
}

/** HTML-family self-closing options for NAPI */
export interface HtmlSelfClosingHtmlOptionsNapi {
  void?: string;
  normal?: string;
  component?: string;
}

export declare function printCssAst(
  ast: any,
  options?: CssCompileOptionsNapi | undefined | null,
): CssCompileResultNapi;

/** Prop control for NAPI */
export interface PropControlNapi {
  name: string;
  control: string;
  defaultValue?: any;
  description?: string;
  required: boolean;
  options: Array<SelectOptionNapi>;
  range?: RangeConfigNapi;
  group?: string;
}

export interface PropDefinitionNapi {
  name: string;
  propType: string;
  required: boolean;
  defaultValue?: any;
}

/** Range config for NAPI */
export interface RangeConfigNapi {
  min: number;
  max: number;
  step?: number;
}

/** Related location for diagnostic (NAPI) */
export interface RelatedLocationNapi {
  message: string;
  start: number;
  end: number;
  filename?: string;
}

export declare function resolveDesignTokenReferences(categories: string): string;

export declare function resolveViteAliasRequest(
  id: string,
  aliasRules: Array<CssAliasRuleNapi>,
): string | null;

export declare function resolveViteCssImports(
  css: string,
  importer: string,
  aliasRules: Array<CssAliasRuleNapi>,
  isDev?: boolean | undefined | null,
  devUrlBase?: string | undefined | null,
): string;

export declare function resolveViteRelativeImport(id: string, importer: string): string | null;

export declare function resolveViteVuePath(
  root: string,
  id: string,
  importer?: string | undefined | null,
): string;

export declare function rewriteSfcTemplateAssetReferences(
  code: string,
  assets: Array<TemplateAssetUrlNapi>,
): string;

export declare function rewriteViteDynamicTemplateImports(
  code: string,
  aliasRules: Array<DynamicImportAliasRuleNapi>,
): string;

export declare function rewriteViteImportMetaGlobBase(
  code: string,
  importer: string,
  root: string,
): string;

export declare function rewriteViteStaticAssetUrls(
  code: string,
  aliasRules: Array<DynamicImportAliasRuleNapi>,
): string;

export declare function runCli(args: Array<string>): void;

export declare function scopeViteCssForPipeline(css: string, scopeId: string): string;

/** Select option for NAPI */
export interface SelectOptionNapi {
  label: string;
  value: any;
}

export interface SfcBlockAttributeNapi {
  name: string;
  value?: string;
}

export interface SfcCompileOptionsNapi {
  filename?: string;
  mode?: string;
  sourceMap?: boolean;
  ssr?: boolean;
  vapor?: boolean;
  customRenderer?: boolean;
  customElements?: Array<string>;
  templateSyntax?: string;
  experimentalInTagComments?: boolean;
  experimentalPatternedTemplate?: boolean;
  experimentalServerScript?: boolean;
  runtimeModuleName?: string;
  runtimeGlobalName?: string;
  vueVersion?: string;
  /** Preserve TypeScript in output when true */
  isTs?: boolean;
  /** Scope ID for scoped CSS (e.g., "data-v-abc123") */
  scopeId?: string;
}

export interface SfcCompileResultNapi {
  code: string;
  /** Source Map v3 document (JSON) describing `code`, present only when
   * `sourceMap` was requested and at least one authored line could be
   * anchored (#3399). Its single `sources` entry is the authored `.vue` path. */
  map?: string;
  css?: string;
  errors: Array<string>;
  warnings: Array<string>;
  templateHash?: string;
  styleHash?: string;
  scriptHash?: string;
  hasScoped: boolean;
  styles: Array<StyleBlockNapi>;
  customBlocks: Array<CustomBlockNapi>;
  macroArtifacts: Array<MacroArtifactNapi>;
}

export interface SfcParseOptionsNapi {
  filename?: string;
}

export interface SfcSrcInfoNapi {
  scriptSrc?: string;
  templateSrc?: string;
}

export declare function shouldApplyViteDefineInVirtualModule(key: string): boolean;

export declare function splitViteIdQuery(id: string): ViteIdPartsNapi;

export declare function stripSfcScopedCssComments(css: string): string;

export interface StyleBlockNapi {
  content: string;
  src?: string;
  lang?: string;
  scoped: boolean;
  module: boolean;
  moduleName?: string;
  index: number;
}

export interface TemplateAssetTagRuleNapi {
  tag: string;
  attrs: Array<string>;
}

export interface TemplateAssetUrlNapi {
  url: string;
  varName: string;
}

export declare function toViteBrowserImportPrefix(replacement: string): string;

export declare function transformViteCssVarsForPipeline(css: string, scopeId: string): string;

/**
 * Perform type checking on a Vue SFC
 *
 * This performs AST-based type analysis without requiring a TypeScript compiler.
 * For full type checking, use the CLI with Corsa integration.
 */
export declare function typeCheck(
  source: string,
  options?: TypeCheckOptionsNapi | undefined | null,
): TypeCheckResultNapi;

/** Batch type check SFC files matching a glob pattern (native multithreading) */
export declare function typeCheckBatch(
  pattern: string,
  options?: TypeCheckOptionsNapi | undefined | null,
): BatchTypeCheckResultNapi;

/** Type check capabilities result */
export interface TypeCheckCapabilitiesNapi {
  mode: string;
  description: string;
  checks: Array<TypeCheckCapabilityNapi>;
  notes: Array<string>;
}

/** Type check capabilities info */
export interface TypeCheckCapabilityNapi {
  name: string;
  description: string;
  severity: string;
}

/** Type check options for NAPI */
export interface TypeCheckOptionsNapi {
  filename?: string;
  strict?: boolean;
  includeVirtualTs?: boolean;
  checkProps?: boolean;
  checkEmits?: boolean;
  checkTemplateBindings?: boolean;
  checkReactivity?: boolean;
  checkSetupContext?: boolean;
  checkInvalidExports?: boolean;
  checkFallthroughAttrs?: boolean;
  legacyVue2?: boolean;
}

/** Type check result for NAPI */
export interface TypeCheckResultNapi {
  diagnostics: Array<TypeDiagnosticNapi>;
  virtualTs?: string;
  errorCount: number;
  warningCount: number;
  analysisTimeMs?: number;
}

/** Type diagnostic for NAPI */
export interface TypeDiagnosticNapi {
  severity: string;
  message: string;
  start: number;
  end: number;
  code?: string;
  help?: string;
  related: Array<RelatedLocationNapi>;
}

export declare function validateDesignTokenReference(
  tokenMap: string,
  reference: string,
  selfPath?: string | undefined | null,
): string;

export interface ViteDevMiddlewareRewriteNapi {
  cleanedUrl: string;
  fsPath: string;
}

export interface ViteIdPartsNapi {
  request: string;
  querySuffix: string;
}

export interface VitePluginRequestNapi {
  /** Path segment before the query string. */
  path: string;
  /** Query suffix including the leading `?`, or an empty string. */
  querySuffix: string;
  /** Path normalized for macro virtual modules (`.vue.ts[x]` -> `.vue`). */
  normalizedVuePath: string;
  /** For `\0...` virtual macro IDs, the real path without the virtual prefix. */
  strippedVirtualPath?: string;
  /** Whether this ID is a Vize-compiled virtual Vue module. */
  isVizeVirtual: boolean;
  /** Whether this ID is a Vize SSR virtual Vue module. */
  isVizeSsrVirtual: boolean;
  /** Real `.vue` path extracted from a Vize virtual Vue module ID. */
  vizeVirtualPath?: string;
  /** Build-safe ID with Vite's `/@fs` prefix removed when present. */
  normalizedFsId?: string;
  /** Whether the query contains `macro=true`. */
  hasMacroQuery: boolean;
  /** Whether the query contains `definePage`. */
  hasDefinePageQuery: boolean;
  /** Whether this is a `\0` virtual ID carrying a macro query. */
  isMacroVirtualId: boolean;
  /** Whether the request points at a Vue SFC after macro normalization. */
  isVueSfcPath: boolean;
  /** Whether the request is a Vite Vue style virtual query. */
  isVueStyleQuery: boolean;
  /** Style block language, defaulting to `css` for style virtual queries. */
  styleLang?: string;
  /** Style block index for style virtual queries. */
  styleIndex?: number;
  /** Scoped attribute value for style virtual queries. */
  styleScoped?: string;
  /** Whether the style query carries a CSS modules marker. */
  hasStyleModule: boolean;
  /** Extension suffix Vite should see for the style pipeline. */
  styleVirtualSuffix?: string;
  /** Vue boundary file kind: `client`, `server`, or undefined. */
  boundaryKind?: string;
}

export interface VitePrecompileChunkOptionsNapi {
  maxBytes?: number;
  metadata?: Array<VitePrecompileFileMetadataEntryNapi>;
}

export interface VitePrecompileDiffNapi {
  changedFiles: Array<string>;
  deletedFiles: Array<string>;
}

export interface VitePrecompileFileMetadataEntryNapi {
  path: string;
  mtimeMs: number;
  size: number;
}

export interface VitePrecompileFileMetadataNapi {
  mtimeMs: number;
  size: number;
}

export declare function wrapSfcScopedPreprocessorStyle(
  content: string,
  scoped?: string | undefined | null,
  lang?: string | undefined | null,
): string;
