/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type LintPreset =
  | "happy-path"
  | "opinionated"
  | "essential"
  | "incremental"
  | "ecosystem"
  | "nuxt";

export type RuleSeverity = "off" | "warn" | "error";

export type RuleCategory = "correctness" | "suspicious" | "style" | "perf" | "a11y" | "security";

/**
 * Host Vue runtime version for opt-in compatibility modes
 */
export type VueVersion = "3" | "2.7" | "2" | "1" | "0.11" | "0.10";

/**
 * Configuration file for vize - High-performance Vue.js toolchain
 */
export interface VizeConfig {
  /**
   * Human-readable entry name for inspect output and diagnostics
   */
  name?: string;
  /**
   * Directory used as the base for scoped file patterns and relative paths
   */
  basePath?: string;
  /**
   * Glob patterns this config applies to
   */
  files?: string[];
  /**
   * Glob patterns this config excludes
   */
  ignores?: string[];
  /**
   * Base config files or presets to compose
   */
  extends?: string | string[];
  /**
   * Vue dialect profile for standalone HTML documents; when absent the dialect is detected structurally per document
   */
  dialect?: "vue" | "petite-vue";
  compiler?: CompilerConfig;
  experimentals?: {
    [k: string]:
      | boolean
      | {
          [k: string]: unknown;
        }
      | null;
  };
  vite?: VitePluginConfig;
  linter?: LinterConfig;
  typeChecker?: TypeCheckerConfig;
  formatter?: FormatterConfig;
  languageServer?: LanguageServerConfig;
  lsp?: LanguageServerConfig;
  musea?: MuseaConfig;
  globalTypes?: GlobalTypesConfig;
  /**
   * Scoped config entries for monorepos and workspaces
   */
  entries?: VizeConfigEntry[];
}
/**
 * Vue compiler options
 */
export interface CompilerConfig {
  /**
   * Compilation mode
   */
  mode?: "module" | "function";
  /**
   * Enable Vapor mode compilation
   */
  vapor?: boolean;
  /**
   * Default output mode for .jsx/.tsx components without a "use vue:*" directive
   */
  jsxMode?: "vdom" | "vapor";
  /**
   * JSX semantics for projects migrating from @vue/babel-plugin-jsx
   */
  jsxCompat?: "native" | "babel";
  /**
   * Treat lowercase non-HTML tags as custom renderer elements
   */
  customRenderer?: boolean;
  /**
   * Tag patterns that compile as custom elements instead of Vue components
   */
  customElements?: string[];
  /**
   * Enable SSR mode
   */
  ssr?: boolean;
  /**
   * Template syntax compatibility mode
   */
  templateSyntax?: "standard" | "strict" | "quirks";
  /**
   * Enable source map generation
   */
  sourceMap?: boolean;
  /**
   * Prefix template identifiers with _ctx
   */
  prefixIdentifiers?: boolean;
  /**
   * Hoist static nodes
   */
  hoistStatic?: boolean;
  /**
   * Cache v-on handlers
   */
  cacheHandlers?: boolean;
  /**
   * Enable TypeScript parsing in <script> blocks
   */
  isTs?: boolean;
  /**
   * Script file extension for generated output
   */
  scriptExt?: "ts" | "js";
  /**
   * Module name for runtime imports
   */
  runtimeModuleName?: string;
  /**
   * Global variable name for runtime (IIFE builds)
   */
  runtimeGlobalName?: string;
  compatibility?: CompilerCompatibilityConfig;
}
/**
 * Opt-in compatibility features for unsupported host/runtime combinations
 */
export interface CompilerCompatibilityConfig {
  vueVersion?: VueVersion;
  /**
   * Delegate .vue compilation to the host Vue compiler for legacy Vue runtimes
   */
  hostCompiler?: boolean;
  /**
   * Enable <script setup> when emitting function-body output for CDN/global Vue usage
   */
  scriptSetupInStandalone?: boolean;
  /**
   * Allow Vapor output for Options API SFCs when Vapor mode is enabled
   */
  optionsApiVapor?: boolean;
  /**
   * Nuxt major line for opt-in Nuxt compatibility behavior
   */
  nuxtVersion?: 2 | 3 | 4;
  /**
   * webpack major line for opt-in bundler compatibility behavior
   */
  webpackVersion?: 4 | 5;
}
export interface VitePluginConfig {
  /**
   * Files to include in compilation (glob patterns or strings)
   */
  include?: string | RegExp | (string | RegExp)[];
  /**
   * Files to exclude from compilation (glob patterns or strings)
   */
  exclude?: string | RegExp | (string | RegExp)[];
  /**
   * Glob patterns to scan for .vue files during pre-compilation
   */
  scanPatterns?: string[];
  /**
   * Glob patterns to ignore during pre-compilation
   */
  ignorePatterns?: string[];
}
/**
 * Linter options
 */
export interface LinterConfig {
  /**
   * Enable linting
   */
  enabled?: boolean;
  /**
   * Built-in lint preset
   */
  preset?: "happy-path" | "opinionated" | "essential" | "incremental" | "ecosystem" | "nuxt";
  /**
   * Enable native type-aware lint rules from the active lint configuration
   */
  typeAware?: boolean;
  /**
   * Rules to enable/disable
   */
  rules?: {
    [k: string]: "off" | "warn" | "error";
  };
  ruleOptions?: LintRuleOptions;
  /**
   * Category-level severity overrides
   */
  categories?: {
    correctness?: "off" | "warn" | "error";
    suspicious?: "off" | "warn" | "error";
    style?: "off" | "warn" | "error";
    perf?: "off" | "warn" | "error";
    a11y?: "off" | "warn" | "error";
    security?: "off" | "warn" | "error";
  };
}
export interface LintRuleOptions {
  "script/no-restricted-globals"?: NoRestrictedGlobalsOptions;
  "script/no-restricted-members"?: NoRestrictedMembersOptions;
  "vue/component-name-in-template-casing"?: {
    casing?: "PascalCase" | "kebab-case";
  };
  "script/custom-event-name-casing"?: {
    casing?: "camelCase" | "kebab-case";
  };
  "vue/no-mutating-props"?: {
    shallowOnly?: boolean;
  };
  "vue/sfc-element-order"?: {
    order?: (string | string[])[];
  };
  "vue/html-self-closing"?: {
    html?: {
      void?: "always" | "never" | "any";
      normal?: "always" | "never" | "any";
      component?: "always" | "never" | "any";
    };
    svg?: "always" | "never" | "any";
    math?: "always" | "never" | "any";
  };
  "vue/v-on-event-hyphenation"?: "always" | "never";
  "vue/attribute-hyphenation"?: "always" | "never";
  "musea/prefer-design-tokens"?: MuseaPreferDesignTokensOptions;
}
export interface NoRestrictedGlobalsOptions {
  globals?: RestrictedGlobal[];
}
export interface RestrictedGlobal {
  name: string;
  message?: string;
}
export interface NoRestrictedMembersOptions {
  members?: RestrictedMember[];
}
export interface RestrictedMember {
  object: string;
  property: string;
  message?: string;
}
export interface MuseaPreferDesignTokensOptions {
  tokens?: MuseaDesignToken[];
}
export interface MuseaDesignToken {
  /**
   * Token path, for example color.primary
   */
  path: string;
  /**
   * Primitive CSS value to match, for example #3b82f6
   */
  value: string;
  /**
   * Token tier shown in diagnostics
   */
  tier?: string;
}
export interface TypeCheckerConfig {
  /**
   * Enable type checking
   */
  enabled?: boolean;
  /**
   * Enable strict mode
   */
  strict?: boolean;
  /**
   * Check component props
   */
  checkProps?: boolean;
  /**
   * Check component emits
   */
  checkEmits?: boolean;
  /**
   * Check template bindings
   */
  checkTemplateBindings?: boolean;
  /**
   * Check reactivity loss patterns
   */
  checkReactivity?: boolean;
  /**
   * Check setup context violations
   */
  checkSetupContext?: boolean;
  /**
   * Check invalid exports in <script setup>
   */
  checkInvalidExports?: boolean;
  /**
   * Check fallthrough attrs on multi-root templates
   */
  checkFallthroughAttrs?: boolean;
  /**
   * Resolve Vue 3 Options API template bindings during type checking
   */
  optionsApi?: boolean;
  /**
   * Enable Vue 2.7 / Nuxt 2 Options API template binding support
   */
  legacyVue2?: boolean;
  /**
   * Opt-in type-checking of .jsx/.tsx Vue components (#1497). Default-off so mixed Vue/React repositories do not accidentally route React .tsx through the Vue JSX checker. Set to true to route .jsx/.tsx through the Vize JSX virtual-TS path.
   */
  jsxTypecheck?: boolean;
  /**
   * Path to tsconfig.json
   */
  tsconfig?: string;
  /**
   * Path to the Corsa executable. This is the canonical runtime key; tsgoPath is kept as a compatibility alias.
   */
  corsaPath?: string;
  /**
   * Deprecated alias for typeChecker.corsaPath
   */
  tsgoPath?: string;
  /**
   * Path to a .d.ts file that declares template globals
   */
  globalsFile?: string;
  /**
   * Reserved Corsa server count. The direct project-session runner currently supports only 1.
   */
  servers?: number;
}
/**
 * Formatter options
 */
export interface FormatterConfig {
  /**
   * Max line width
   */
  printWidth?: number;
  /**
   * Indentation width
   */
  tabWidth?: number;
  /**
   * Use tabs for indentation
   */
  useTabs?: boolean;
  /**
   * Print semicolons
   */
  semi?: boolean;
  /**
   * Use single quotes
   */
  singleQuote?: boolean;
  /**
   * Use single quotes in JSX
   */
  jsxSingleQuote?: boolean;
  /**
   * Trailing commas
   */
  trailingComma?: "all" | "none" | "es5";
  /**
   * Print spaces between brackets in object literals
   */
  bracketSpacing?: boolean;
  /**
   * Keep > on the last line of multiline tags
   */
  bracketSameLine?: boolean;
  /**
   * Arrow parens mode
   */
  arrowParens?: "always" | "avoid";
  /**
   * End-of-line mode
   */
  endOfLine?: "lf" | "crlf" | "cr" | "auto";
  /**
   * Object property quoting mode
   */
  quoteProps?: "as-needed" | "consistent" | "preserve";
  /**
   * Force one attribute per line
   */
  singleAttributePerLine?: boolean;
  /**
   * Indent script and style blocks
   */
  vueIndentScriptAndStyle?: boolean;
  /**
   * Sort attributes
   */
  sortAttributes?: boolean;
  /**
   * Attribute ordering strategy
   */
  attributeSortOrder?: "alphabetical" | "as-written";
  /**
   * Merge bind and non-bind attrs for sorting
   */
  mergeBindAndNonBindAttrs?: boolean;
  /**
   * Maximum attributes per line before wrapping
   */
  maxAttributesPerLine?: number;
  /**
   * Custom attribute groups
   */
  attributeGroups?: string[][];
  /**
   * Normalize directive shorthands
   */
  normalizeDirectiveShorthands?: boolean;
  /**
   * Sort SFC blocks in canonical order
   */
  sortBlocks?: boolean;
}
/**
 * Language server options
 */
export interface LanguageServerConfig {
  /**
   * Enable the language server
   */
  enabled?: boolean;
  /**
   * Enable lint diagnostics
   */
  lint?: boolean;
  /**
   * Deprecated alias for lint
   */
  diagnostics?: boolean;
  /**
   * Enable project type checking diagnostics
   */
  typecheck?: boolean;
  /**
   * Enable editor-oriented IDE features
   */
  editor?: boolean;
  /**
   * Enable Vue ecosystem lint and editor helpers
   */
  ecosystem?: boolean;
  /**
   * Enable Vue 2.7 / Nuxt 2 editor and type-checking compatibility
   */
  legacyVue2?: boolean;
  /**
   * Enable completions
   */
  completion?: boolean;
  /**
   * Enable TypeScript signature help
   */
  signatureHelp?: boolean;
  /**
   * Enable hover information
   */
  hover?: boolean;
  /**
   * Enable go-to-definition
   */
  definition?: boolean;
  /**
   * Enable reference search
   */
  references?: boolean;
  /**
   * Enable document symbols
   */
  documentSymbols?: boolean;
  /**
   * Enable workspace symbols
   */
  workspaceSymbols?: boolean;
  /**
   * Enable formatting via the language server
   */
  formatting?: boolean;
  /**
   * Enable code actions
   */
  codeActions?: boolean;
  /**
   * Enable rename support
   */
  rename?: boolean;
  /**
   * Enable code lenses
   */
  codeLens?: boolean;
  /**
   * Enable semantic tokens
   */
  semanticTokens?: boolean;
  /**
   * Enable document links
   */
  documentLinks?: boolean;
  /**
   * Enable folding ranges
   */
  foldingRanges?: boolean;
  /**
   * Enable inlay hints
   */
  inlayHints?: boolean;
  /**
   * Enable file rename edits
   */
  fileRename?: boolean;
  /**
   * Enable Corsa-backed IDE features
   */
  corsa?: boolean;
  /**
   * Deprecated alias for corsa
   */
  tsgo?: boolean;
}
/**
 * Musea component gallery options
 */
export interface MuseaConfig {
  /**
   * Glob patterns for art files
   */
  include?: string[];
  /**
   * Glob patterns to exclude
   */
  exclude?: string[];
  /**
   * Base path for gallery
   */
  basePath?: string;
  /**
   * Enable Storybook compatibility
   */
  storybookCompat?: boolean;
  /**
   * Enable inline art detection in .vue files
   */
  inlineArt?: boolean;
  vrt?: MuseaVrtConfig;
  a11y?: MuseaA11yConfig;
  autogen?: MuseaAutogenConfig;
}
/**
 * VRT (Visual Regression Testing) configuration
 */
export interface MuseaVrtConfig {
  /**
   * Threshold for pixel comparison (0-1)
   */
  threshold?: number;
  /**
   * Output directory for screenshots
   */
  outDir?: string;
  /**
   * Viewport sizes
   */
  viewports?: MuseaViewport[];
}
export interface MuseaViewport {
  /**
   * Viewport width
   */
  width: number;
  /**
   * Viewport height
   */
  height: number;
  /**
   * Viewport name
   */
  name?: string;
}
/**
 * A11y configuration
 */
export interface MuseaA11yConfig {
  /**
   * Enable a11y checking
   */
  enabled?: boolean;
  /**
   * Axe-core rules to enable/disable
   */
  rules?: {
    [k: string]: boolean;
  };
}
/**
 * Autogen configuration
 */
export interface MuseaAutogenConfig {
  /**
   * Enable auto-generation of variants
   */
  enabled?: boolean;
  /**
   * Max variants to generate per component
   */
  maxVariants?: number;
}
/**
 * Global type declarations
 */
export interface GlobalTypesConfig {
  [k: string]: string | GlobalTypeDeclaration;
}
/**
 * Global type declaration
 */
export interface GlobalTypeDeclaration {
  /**
   * TypeScript type string
   */
  type: string;
  /**
   * Default value
   */
  defaultValue?: string;
}
/**
 * Scoped Vize config entry for monorepos and workspaces
 */
export interface VizeConfigEntry {
  /**
   * Human-readable entry name for inspect output and diagnostics
   */
  name?: string;
  /**
   * Directory used as the base for scoped file patterns and relative paths
   */
  basePath?: string;
  /**
   * Glob patterns this entry applies to
   */
  files?: string[];
  /**
   * Glob patterns this entry excludes
   */
  ignores?: string[];
  /**
   * Base config files or presets to compose
   */
  extends?: string | string[];
  /**
   * Vue dialect profile for standalone HTML documents; when absent the dialect is detected structurally per document
   */
  dialect?: "vue" | "petite-vue";
  compiler?: CompilerConfig;
  experimentals?: {
    [k: string]:
      | boolean
      | {
          [k: string]: unknown;
        }
      | null;
  };
  vite?: VitePluginConfig;
  linter?: LinterConfig;
  typeChecker?: TypeCheckerConfig;
  formatter?: FormatterConfig;
  languageServer?: LanguageServerConfig;
  lsp?: LanguageServerConfig;
  musea?: MuseaConfig;
  globalTypes?: GlobalTypesConfig;
}
